package com.MessagingProtocol;

public enum MessageType {
    FriendRequest_Message,
    FriendReply_Message,
    FriendsRequest_Message,
    FriendsReply_Message,
    UploadAudioReply_Message,
    UploadAudioRequest_Message,
    UploadImageReply_Message,
    UploadImageRequest_Message,
    LocationUpdate_Message,
    Identification_Message,
    AuthenticationSuccessful_Message,
    AuthenticationFailed_Message,
    SignOut_Message,
    Text_Message,
    EventCreationRequest_Message,
    EventCreationReply_Message,
    SubscribeToEventRequest_Message,
    SubscribeToEventReply_Message,
    UnsubscribeFromEventRequest_Message,
    UnsubscribeFromEventReply_Message,
    GetAllEventsRequest_Message,
    GetAllEventsReply_Message,
    EventChat_Message,
    SyncMissedMessagesRequest_Message,
    SyncMissedMessagesReply_Message,
    ProfilePictureUpdate_Message
}
